server:
  port: 8081

# db 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-mysql-sgp1-08164-seb4-catchtable-do-user-15080737-0.c.db.ondigitalocean.com:25060/defaultdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: seb4
    password: AVNS_uvnJKn8OLOq3UfF2jj1
  thymeleaf:
    cache: false
  sql:
    init:
      platform: mysql
      # mode: always
  web:
    resources:
      static-locations: classpath:/static/

  # spring data jpa 설정
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      # create -> 프로젝트를 실행할때마다 테이블이 다시 만들어짐
      # update -> 바뀌는게 있을때만 변경하고 아닌 경우에는 기존 테이블 유지
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
    database: mysql
